# We specify the version of docker compose
version: "3.9"
# We specify the different services
services: 
    # The api
    backend:
        # the build folder
        image: backend
        build: 
            context: ./backend
            dockerfile: ./Dockerfile
        container_name: backend
        # the ports to map
        ports: 
            - 8082:8082
            - 9229:9229
            - 9230:9230
        # start after the database
        depends_on: 
            - db
            - phpmyadmin
        # The differents networks
        networks:
            - private
            - public
    # The client
    frontend:
        # the build folder
        image: frontend
        build: 
            context: ./frontend
            dockerfile: ./Dockerfile
        container_name: frontend
        # the ports to map
        ports: 
            - 3000:3000
        # start after the database
        depends_on:
            - db
            - phpmyadmin
        # The differents networks
        networks:
            - public
    # The database
    db:
        # https://hub.docker.com/_/mysql
        image: mysql:latest
        container_name: db
        # The differents networks
        networks:
            - private
        # Ports
        ports:
            - "6033:3306"
        # The shared folder
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    # The database
    phpmyadmin:
        # https://hub.docker.com/_/phpmyadmin
        image: phpmyadmin:latest
        container_name: pma
        restart: always
        # The differents networks
        networks:
            - private
        # start after the database
        depends_on:
            - db
        # Links to the db
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        # Set up the port
        ports:
            - 30002:80
# We specify the different networks
networks:
    public:
    private:
# We specify the differents shared folders
volumes:
    db-data: